sudo: required

language: go

go:
  - "1.10.x"

services:
  - docker

before_install:
  - go get -u -v github.com/gorilla/mux github.com/mattn/go-sqlite3 github.com/rs/cors github.com/stretchr/testify  

script:
- ./deploy.sh ci
